[package]
name = "amwapos-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "AMWAPOS domain, persistence and application services"

[dependencies]
rusqlite.workspace = true
argon2.workspace = true
ulid.workspace = true
sha2.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
rand.workspace = true
hex.workspace = true
csv.workspace = true
fs4.workspace = true
hmac.workspace = true
tracing.workspace = true
spake2 = "0.4"
chacha20poly1305 = "0.10"
hkdf = "0.12"
rustybuzz = "0.20"
unicode-bidi = "0.3"
ab_glyph_rasterizer = "0.1"
flate2 = "1"
base64 = "0.22"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_Graphics_Printing", "Win32_Graphics_Gdi"] }

[dev-dependencies]
tempfile.workspace = true
