//! AMWAPOS core: domain rules, persistence and application services.
//!
//! Layering: `commands` (transport-neutral dispatch) → `service`/feature
//! modules (auth, validation, transactions) → pure domain (`money`,
//! `pricing`) and repositories (SQL inside feature modules).

pub mod address;
pub mod ai;
pub mod ai_actions;
pub mod ai_helpers;
pub mod ai_tools;
pub mod ai_workspace;
pub mod audit;
pub mod auth;
pub mod backup;
pub mod barcodes;
pub mod branches;
pub mod cases;
pub mod catalog;
pub mod catalogue;
pub mod channel;
pub mod commands;
pub mod companion;
pub mod credit;
pub mod customers;
pub mod dayclose;
pub mod db;
pub mod docintel;
pub mod eod;
pub mod error;
pub mod expenses;
pub mod idempotency;
pub mod ids;
pub mod importer;
pub mod inventory;
pub mod lots;
pub mod loyalty;
pub mod messaging;
pub mod migration;
pub mod money;
pub mod ocrflow;
pub mod orders;
pub mod payables;
pub mod pdf;
pub mod pos;
pub mod pricing;
pub mod printing;
pub mod procurement;
pub mod product_images;
pub mod purchasing;
pub mod raster;
pub mod receipt;
pub mod refunds;
pub mod registers;
pub mod replenish;
pub mod reports;
pub mod requisitions;
pub mod reservations;
pub mod riders;
pub mod sales;
pub mod service;
pub mod settings;
pub mod setup;
pub mod shifts;
pub mod supplier_returns;
pub mod sync;
pub mod system;
pub mod tickets;
pub mod time;
pub mod transfers;
pub mod users;
pub mod validate;
pub mod voids;
pub mod wa_catalog;
pub mod wa_contacts;
pub mod waorders;
pub mod waste;

pub use error::{AppError, AppResult, ErrorCode};
pub use service::AppCore;
